// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SijidenRolesColumns holds the columns for the "sijiden_roles" table.
	SijidenRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "redirect_url", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SijidenRolesTable holds the schema information for the "sijiden_roles" table.
	SijidenRolesTable = &schema.Table{
		Name:       "sijiden_roles",
		Columns:    SijidenRolesColumns,
		PrimaryKey: []*schema.Column{SijidenRolesColumns[0]},
	}
	// SijidenUsersColumns holds the columns for the "sijiden_users" table.
	SijidenUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "phone_number", Type: field.TypeString},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "phone_verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SijidenUsersTable holds the schema information for the "sijiden_users" table.
	SijidenUsersTable = &schema.Table{
		Name:       "sijiden_users",
		Columns:    SijidenUsersColumns,
		PrimaryKey: []*schema.Column{SijidenUsersColumns[0]},
	}
	// SijidenUserRolesColumns holds the columns for the "sijiden_user_roles" table.
	SijidenUserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// SijidenUserRolesTable holds the schema information for the "sijiden_user_roles" table.
	SijidenUserRolesTable = &schema.Table{
		Name:       "sijiden_user_roles",
		Columns:    SijidenUserRolesColumns,
		PrimaryKey: []*schema.Column{SijidenUserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sijiden_user_roles_sijiden_roles_user_roles",
				Columns:    []*schema.Column{SijidenUserRolesColumns[1]},
				RefColumns: []*schema.Column{SijidenRolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "sijiden_user_roles_sijiden_users_user_roles",
				Columns:    []*schema.Column{SijidenUserRolesColumns[2]},
				RefColumns: []*schema.Column{SijidenUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SijidenRolesTable,
		SijidenUsersTable,
		SijidenUserRolesTable,
	}
)

func init() {
	SijidenRolesTable.Annotation = &entsql.Annotation{
		Table: "sijiden_roles",
	}
	SijidenUsersTable.Annotation = &entsql.Annotation{
		Table: "sijiden_users",
	}
	SijidenUserRolesTable.ForeignKeys[0].RefTable = SijidenRolesTable
	SijidenUserRolesTable.ForeignKeys[1].RefTable = SijidenUsersTable
	SijidenUserRolesTable.Annotation = &entsql.Annotation{
		Table: "sijiden_user_roles",
	}
}
